#!/bin/bash

case "$1" in
        start)
                su - pcloud -c "export PCLOUD_LOGIN=$PCLOUD_LOGIN
                                /bin/bash /home/pcloud/start.sh"
        ;;
        stop)
                kill -9 $(cat /home/pcloud/.pcloud/pid)
                rm -f /home/pcloud/.pcloud/pid
        ;;
        *)
                echo "Usage: /etc/init.d/pcloud.sh {start|stop}"
                exit 1
        ;;
esac

exit 0
